apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-nginx-deployment
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubectl-runner
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
  verbs:
  - get
  - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-runner-binding
subjects:
- kind: ServiceAccount
  name: sa-nginx-deployment
roleRef:
  kind: Role
  name: kubectl-runner
  apiGroup: rbac.authorization.k8s.io